### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #8.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
Is this ready to be merged?

**Comment by dpryan79** [comment]
@izahn Nothing has changed in it. We can just close it instead.

**Comment by izahn** [comment]
I thought the point was to rebuild it because https://github.com/conda-forge/r-forge-feedstock/runs/8880177870 failed, no?

**Comment by dpryan79** [comment]
We can just hit rerun for that, I think the original hope was that rerendering would fix the token.

**Pull request closed without merging**
